import { type InsertPark } from "@shared/schema";

// Curated list of US National Parks with descriptions and image URLs
export const nationalParksData: InsertPark[] = [
  {
    name: "Yellowstone",
    location: "Wyoming, Montana, Idaho",
    description: "First national park in the world, featuring geothermal wonders including Old Faithful geyser, colorful hot springs, and abundant wildlife like bison, elk, and grizzly bears.",
    imageUrl: "https://images.unsplash.com/photo-1583445095369-9c651e7e5d34?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Yosemite",
    location: "California",
    description: "Iconic granite cliffs, waterfalls including Yosemite Falls, giant sequoias, and the famous Half Dome and El Capitan rock formations in the Sierra Nevada.",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Grand Canyon",
    location: "Arizona",
    description: "Massive canyon carved by the Colorado River, showcasing nearly two billion years of geological history with its colorful layered rock formations.",
    imageUrl: "https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Zion",
    location: "Utah",
    description: "Towering sandstone cliffs, narrow slot canyons including The Narrows, and diverse ecosystems ranging from desert to coniferous forest.",
    imageUrl: "https://images.unsplash.com/photo-1518098268826-37d3abfac8db?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Glacier",
    location: "Montana",
    description: "Pristine wilderness with over 700 lakes, alpine meadows, rugged mountains, and the famous Going-to-the-Sun Road. Home to diverse wildlife and glacially-carved peaks.",
    imageUrl: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Rocky Mountain",
    location: "Colorado",
    description: "Majestic mountain peaks, alpine lakes, diverse wildlife, and over 350 miles of hiking trails. Trail Ridge Road reaches above 12,000 feet elevation.",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Acadia",
    location: "Maine",
    description: "Rugged Atlantic coastline, granite peaks including Cadillac Mountain, forests, and historic carriage roads. First national park east of the Mississippi River.",
    imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Great Smoky Mountains",
    location: "Tennessee, North Carolina",
    description: "Most visited national park featuring ancient mountains, diverse forests, abundant wildlife, and preserved Southern Appalachian culture.",
    imageUrl: "https://images.unsplash.com/photo-1548091861-f8469c572991?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Olympic",
    location: "Washington",
    description: "Diverse ecosystems including temperate rainforests, rugged Pacific coastline, and glacier-capped mountains. Home to unique wildlife and pristine wilderness.",
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Arches",
    location: "Utah",
    description: "Over 2,000 natural stone arches including the iconic Delicate Arch, plus balanced rocks, fins, and pinnacles carved by erosion in red rock desert.",
    imageUrl: "https://images.unsplash.com/photo-1531170222618-0f1e749a4319?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Grand Teton",
    location: "Wyoming",
    description: "Dramatic mountain range rising abruptly from Jackson Hole valley, pristine lakes, alpine terrain, and abundant wildlife including moose and grizzly bears.",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Bryce Canyon",
    location: "Utah",
    description: "Unique geology featuring hoodoos (irregular columns of rock), natural amphitheaters, and brilliant red, orange, and white colored rock formations.",
    imageUrl: "https://images.unsplash.com/photo-1560895198-87000d2cd4cd?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Canyonlands",
    location: "Utah",
    description: "Vast landscape carved by the Colorado and Green Rivers, featuring colorful canyons, mesas, buttes, and the stunning Mesa Arch.",
    imageUrl: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Joshua Tree",
    location: "California",
    description: "Where the Mojave and Colorado deserts meet, featuring unique Joshua trees, rock formations, and stunning desert landscapes perfect for stargazing.",
    imageUrl: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Sequoia",
    location: "California",
    description: "Home to giant sequoia trees including General Sherman, the world's largest tree by volume, plus the High Sierra including Mount Whitney.",
    imageUrl: "https://images.unsplash.com/photo-1542223616-9de9adb5e3e8?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Denali",
    location: "Alaska",
    description: "Centered on Denali, North America's tallest peak at 20,310 feet. Features pristine wilderness, glaciers, tundra, and abundant wildlife including grizzlies.",
    imageUrl: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Death Valley",
    location: "California, Nevada",
    description: "Hottest and driest place in North America, featuring colorful badlands, sand dunes, salt flats, and dramatic elevation changes from below sea level to mountain peaks.",
    imageUrl: "https://images.unsplash.com/photo-1552595386-6a0bc5d9efb1?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Crater Lake",
    location: "Oregon",
    description: "America's deepest lake formed in a collapsed volcano, known for its intense blue color and clarity, surrounded by ancient forests and volcanic landscapes.",
    imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Mount Rainier",
    location: "Washington",
    description: "Iconic volcanic peak covered in glaciers, surrounded by wildflower meadows, old-growth forests, and cascading waterfalls. An active volcano towering over Seattle.",
    imageUrl: "https://images.unsplash.com/photo-1507874457470-272b3c8d8ee2?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Everglades",
    location: "Florida",
    description: "Largest tropical wilderness in the US, featuring unique wetland ecosystem with sawgrass marshes, mangroves, and diverse wildlife including alligators and manatees.",
    imageUrl: "https://images.unsplash.com/photo-1601475021974-4945c92861e8?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Badlands",
    location: "South Dakota",
    description: "Dramatic layered rock formations, deep gorges, and towering spires carved by erosion. Rich in fossils and home to bison and bighorn sheep.",
    imageUrl: "https://images.unsplash.com/photo-1584714268709-c3dd9c92b378?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Shenandoah",
    location: "Virginia",
    description: "Blue Ridge Mountains, scenic Skyline Drive, cascading waterfalls, and diverse forests. Known for stunning fall colors and panoramic valley views.",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Redwood",
    location: "California",
    description: "World's tallest trees, the coast redwoods, some over 350 feet tall. Includes pristine old-growth forests and scenic Pacific coastline.",
    imageUrl: "https://images.unsplash.com/photo-1542223616-9de9adb5e3e8?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
  {
    name: "Capitol Reef",
    location: "Utah",
    description: "Colorful canyons, ridges, buttes, and monoliths forming a 100-mile-long wrinkle in the earth's crust called the Waterpocket Fold.",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop",
    eloRating: 1500,
  },
];
